version: '3.8'

services:
  backend:
    image: ${BACKEND_IMAGE}
    ports:
      - "8080:8080"

  frontend:
    image: ${FRONTEND_IMAGE}
    ports:
      - "80:80"
    environment:
      - BACKEND_SERVER=localhost
    depends_on:
      - backend